const { batchText } = require("./helpers");

const testText =
  "Diane, 7:30 am, February twenty-fourth. Entering town of Twin Peaks. Five miles south of the Canadian border, twelve miles west of the state line. Never seen so many trees in my life. As W.C. Fields would say, I'd rather be here than Philadelphia. It's fifty-four degrees on a slightly overcast day. Weatherman said rain. If you could get paid that kind of money for being wrong sixty percent of the time it'd beat working. Mileage is 79,345, gauge is on reserve, I'm riding on fumes here, I've got to tank up when I get into town. Remind me to tell you how much that is. Lunch was $6.31 at the Lamplighter Inn. That's on Highway Two near Lewis Fork. That was a tuna fish sandwich on whole wheat, a slice of cherry pie and a cup of coffee. Damn good food. Diane, if you ever get up this way, that cherry pie is worth a stop. ... Following a dream I had three years ago, I have become deeply moved by the plight of the Tibetan people, and have been filled with a desire to help them. I also awoke from the same dream realizing that I had subconsciously gained knowledge of a deductive technique, involving mind-body coordination operating hand-in-hand with the deepest level of intuition. ... Diane, 7:30 am, February twenty-fourth. Entering town of Twin Peaks. Five miles south of the Canadian border, twelve miles west of the state line. Never seen so many trees in my life. As W.C. Fields would say, I'd rather be here than Philadelphia. It's fifty-four degrees on a slightly overcast day. Weatherman said rain. If you could get paid that kind of money for being wrong sixty percent of the time it'd beat working. Mileage is 79,345, gauge is on reserve, I'm riding on fumes here, I've got to tank up when I get into town. Remind me to tell you how much that is. Lunch was $6.31 at the Lamplighter Inn. That's on Highway Two near Lewis Fork. That was a tuna fish sandwich on whole wheat, a slice of cherry pie and a cup of coffee. Damn good food. Diane, if you ever get up this way, that cherry pie is worth a stop. ... Following a dream I had three years ago, I have become deeply moved by the plight of the Tibetan people, and have been filled with a desire to help them. I also awoke from the same dream realizing that I had subconsciously gained knowledge of a deductive technique, involving mind-body coordination operating hand-in-hand with the deepest level of intuition.";

const batchedText = batchText(testText, 1500);

console.log("number of batches: ", batchedText.length);
console.log("length of first batch: ", batchedText[0].length);
console.log("full batch data: ", JSON.stringify(batchedText));
